# Generated by Django 2.1.1 on 2018-11-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theater_name2',
        ),
        migrations.RemoveField(
            model_name='time',
            name='movie_name2',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
